[package]
name = "evosim-engine"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
evosim-protocol.workspace = true
serde.workspace = true
serde_json = "1"
tracing.workspace = true
rayon.workspace = true
wgpu.workspace = true
pollster.workspace = true
bytemuck.workspace = true
